### ISSUE TITLE
Request for Public Access to Google Drive Checkpoint Files

### ISSUE THREAD

**Issue by Abyss7893** [CrispyFeSo4/AnySR#1]
I want to bring to your attention an issue regarding the accessibility of the checkpoint (.ckpt) files hosted on Google Drive.  Currently, these files require users to request access permission, which can be inconvenient and time-consuming.

To streamline the process for all users, I kindly request that you consider making these checkpoint files publicly accessible without needing access requests.  This change would greatly enhance the user experience and facilitate easier usage of the resources provided by your repository.

Thank you for your attention and continuous efforts to maintain this valuable resource.
![access](https://github.com/CrispyFeSo4/AnySR/assets/98889109/738062fc-95f8-4c1d-adf6-ebf836ac9098)

**Comment by CrispyFeSo4** [comment]
Thanks for pointing that out! I've updated the checkpoint sharing method based on your suggestion. 

This is my first time open-sourcing code, so I’m still learning the ropes. Sorry for any trouble caused. 
I really appreciate your feedback!! If you have any other suggestions, please let me know. (^o^)//

**Comment by Abyss7893** [comment]
Thank you so much for sharing your checkpoint! Your outstanding research and prompt responses are truly impressive. However, I encountered the following issue while running the code locally. I downloaded the checkpoint and executed the commands provided in the demo section of the README. Please let me know if I need to correct something or include any steps. I am eagerly looking forward to your response. (,,・ω・,,)
<img width="830" alt="图片" src="https://github.com/CrispyFeSo4/AnySR/assets/98889109/14ff45b6-2ae3-48d6-b795-74dc42132973">

**Comment by CrispyFeSo4** [comment]
Sorry for the late reply. I found an error in the previous checkpoint config, but I've fixed it and uploaded new checkpoints. Please re-download "anysr_edsr_500.pth" and "anysr_rdn_500.pth" and try again. I apologize for any inconvenience my oversight may have caused. Thank you for your patience!
